log_reg:
  bestpicture_params:
    max_iter: 200
    penalty: 'l2'
    C: 0.008
    random_state: 101
    fit_intercept: True
    intercept_scaling: 0.4

rf:
  bestpicture_params:
    max_depth: 8
    n_estimators: 16
    max_features: 'sqrt'
    min_samples_leaf: 8
    min_samples_split: 6
    random_state: 101

svm:
  bestpicture_params:
    C: 0.1
    gamma: 0.0001
    kernel: 'rbf'
    random_state: 101
      
names:
  class_names: ["non oscar winners", "oscar winners"]